spring.application.name=axibank
spring.datasource.url=jdbc:postgresql://localhost:5432/axiBank
spring.datasource.username=postgres
spring.datasource.password=Xy$9v@4Lp!rT7&ZqM#dW8^fN
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=VGhpcyBJcyBBIFNlY3VyZSBJbmNyZWRpYmxlIFNlY3JldCFLZXkgU3VwZXJTZWN1cmU=
jwt.expiration=86400000